"""Règles pays → continent (alignées sur Online_retail_pipeline.ipynb)."""

# Ordre important : premières correspondances via Country.contains(...)
COUNTRY_CONTINENT_CONTAINS: list[tuple[str, str]] = [
    ("Australia", "Europa"),
    ("EIRE", "Europa"),
    ("Iceland", "Europa"),
    ("United Arab Emirates", "Eurasia"),
    ("Israel", "Eurasia"),
    ("Channel Islands", "Europa"),
    ("Cyprus", "Europa"),
    ("Sweden", "Europa"),
    ("RSA", "Europa"),
    ("Denmark", "Europa"),
    ("Bahrain", "Asia"),
    ("United Kingdom", "Europa"),
    ("Switzerland", "Europa"),
    ("Lithuania", "Europa"),
    ("Czech Republic", "Europa"),
    ("Norway", "Europa"),
    ("Austria", "Europa"),
    ("European Community", "Europa"),
    ("Netherlands", "Europa"),
    ("Spain", "Europa"),
    ("Italy", "Europa"),
    ("Japan", "Asia"),
    ("Finland", "Europa"),
    ("Saudi Arabia", "Eurasia"),
    ("Brazil", "Southamerica"),
    ("France", "Europa"),
    ("Germany", "Europa"),
    ("Poland", "Europa"),
    ("USA", "Northamerica"),
    ("Malta", "Europa"),
    ("Portugal", "Europa"),
    ("Greece", "Europa"),
    ("Singapore", "Asia"),
    ("Lebanon", "Eurasia"),
    ("Canada", "Northamerica"),
]
