paths:
  raw: "s3a://bucket/raw/Online_Retail.csv"
  bronze: "s3a://bucket/bronze"
  silver: "s3a://bucket/silver"
  gold: "s3a://bucket/gold"
spark:
  app_name: "OnlineRetail-prod"
  master: "yarn"
  executor_memory: "8G"
  driver_memory: "8G"
